### ISSUE TITLE
Use Caret (^) for Peer Dependencies

### ISSUE THREAD

**Issue by LankyLou** [infctr/eslint-plugin-typescript-sort-keys#1]
Currently the peer dependencies are specified using a tilde (~) which means that there are peer dependency warnings when using the latest versions of eslint and typescript.

If these were a caret (^) then it would remove these warnings, but still be safe against breaking changes.

**Comment by infctr** [comment]
Thanks for pointing this out! I'll get this fixed

**Comment by LankyLou** [comment]
@infctr looks great thanks
