### ISSUE TITLE
upgrade peer dependency @typescript-eslint/parser v3

### ISSUE THREAD

**Issue by zhaoxuyll** [infctr/eslint-plugin-typescript-sort-keys#18]
warning " > eslint-plugin-typescript-sort-keys@1.2.0" has incorrect peer dependency "@typescript-eslint/parser@^1 || ^2".

**Comment by infctr** [comment]
Haven't really tested the compatibility with typescript-eslint/parser v3 just yet, but sure, it's the next thing to do

**Comment by noelebrun** [comment]
Tested, and PR created @ #19

**Comment by infctr** [comment]
Fixed in #19
