### ISSUE TITLE
Use `^` to pin dependencies

### ISSUE THREAD

**Issue by entropitor** [infctr/eslint-plugin-typescript-sort-keys#21]
When using this plugin in a shared config, all users need to manually install this version, probably because this package is hoisted and I'm guessing this is because of the `~` in the package.json. Is there a reason for this? Could these be changed into a `^`?

**Comment by davidNHK** [comment]
+1 for the same problem.

when used as shared config it need manually install `eslint-plugin-typescript-sort-keys` every project

E.X. 
https://github.com/davidNHK/busybox/blob/development/package.json#L16

**Comment by infctr** [comment]
@entropitor Sorry, I don't follow here, what dependencies should be pinned with `^` instead?

**Comment by entropitor** [comment]
I've got a Pull Request that should fix it (https://github.com/infctr/eslint-plugin-typescript-sort-keys/pull/24)

I'd personally also advise this to do for the devDependencies but I don't think it's required to make it work.

**Comment by infctr** [comment]
@entropitor Published latest changes, please give it a try and let me know whether it works as expected

**Comment by entropitor** [comment]
@infctr I guess the problem is that this package is still using an old version of `experimental-utils` so when you are using it in a shared config package together with `@typescript-eslint`, it will fail to install properly because of hoisting. This module is not hoisted to the top level so it's not in the right place for eslint.

Would it be hard to bump the version for @typescript-eslint/experimental-utils? There doesn't seem to be breaking changes: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/experimental-utils/CHANGELOG.md

**Comment by infctr** [comment]
@entropitor There were a couple of breaking changes concerning typings, that was the reason it was pinned with `~` in the first place. I'll have a look and try to update it
