### ISSUE TITLE
Consider contributing features up to typescript-eslint?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [infctr/eslint-plugin-typescript-sort-keys#50]
Hi! I'm a maintainer on [typescript-eslint](https://typescript-eslint.io) and just stumbled onto this plugin from a feature request on the [typescript-eslint `member-ordering` rule](https://typescript-eslint.io/rules/member-ordering) (https://github.com/typescript-eslint/typescript-eslint/issues/4859). It looks like much of this plugin's functionality is already in `member-ordering`. 

Is there anything in particular you'd want to be added to `member-ordering` that doesn't exist in it already?

**Comment by infctr** [comment]
Hey @JoshuaKGoldberg 
Thanks for reaching out! There are many plugin users on npm, so I would expect all the of the options from [interface](https://github.com/infctr/eslint-plugin-typescript-sort-keys/blob/master/docs/rules/interface.md) and [string-enum](https://github.com/infctr/eslint-plugin-typescript-sort-keys/blob/master/docs/rules/string-enum.md) rules to be supported in `member-ordering`

**Comment by infctr** [comment]
I can see that `requiredFirst: true` is not supported in `member-ordering`, is it?

**Comment by JoshuaKGoldberg** [comment]
Ooh, it isn't, no. Now that I'm taking a deeper look I see the `natural` sorting option isn't either.

Are you up for filing an issue on typescript-eslint and/or sending a PR in? No worries if that's a sudden unexpected ask you don't have time for 😄, I can take on whatever you don't. 

I'll also note our docs page isn't great right now and I plan on fixing it up soon: https://github.com/typescript-eslint/typescript-eslint/issues/4861

**Comment by zachbryant** [comment]
Just as a user looking between these two, the reason I'm choosing `eslint-plugin-typescript-sort-keys` is the auto-fixer

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
