### ISSUE TITLE
Add support for TypeScript >= 5.0

### ISSUE THREAD

**Issue by schoero** [infctr/eslint-plugin-typescript-sort-keys#57]
Please consider adding support for TypeScript >= 5.0.

Currently I get the following error when I try to install this plugin with TypeScript 5.0.2 installed in my project:

```bash
...
npm ERR! Found: typescript@5.0.2
npm ERR! node_modules/typescript
npm ERR!   typescript@"^5.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^3 || ^4" from eslint-plugin-typescript-sort-keys@2.1.0
npm ERR! node_modules/eslint-plugin-typescript-sort-keys
...
```

**Comment by kai-dorschner-twinsity** [comment]
I've created a PR for you @schoero https://github.com/infctr/eslint-plugin-typescript-sort-keys/pull/58
Next time you could invest these 2 mins yourself and take the credits.
