### ISSUE TITLE
Publish new version with @typescript-eslint/parser@6

### ISSUE THREAD

**Issue by PredokMiF** [infctr/eslint-plugin-typescript-sort-keys#74]
Publish please new version of plugin with `peerDependencies` `"@typescript-eslint/parser": "^6"`.
I was created my own eslint rules pack with `eslint-plugin-typescript-sort-keys`, but when install the pack - `@typescript-eslint/parser` v5 conflict with v6 wrom other packages and `npm install` put it in to nested (not root) `node_modules` and cant find it, when start eslint.

**Comment by Goldziher** [comment]
same, this issue is annoying
