### ISSUE TITLE
Consider allowing "@typescript-eslint/parser": "^8" in peer dependencies

### ISSUE THREAD

**Issue by GBrachetta** [infctr/eslint-plugin-typescript-sort-keys#79]
Hi, could you consider allowing:

"@typescript-eslint/parser": "^6 || ^7 || **^8**"

in your peer deps so we wouldn't receive the warning when using eslint configs that already upgraded to the v.8 of the parser.

Thanks!

**Comment by StructByLightning** [comment]
There's a PR for it: https://github.com/infctr/eslint-plugin-typescript-sort-keys/pull/78

**Comment by GBrachetta** [comment]
I see. No reaction from the dev though...
